
sourceDir: '.'
destinationDir: '_site'
templateDir: templates

includeFiles: [
  png,
  gif,
  webp,
  html,
  js,
  css,
  otf,
  ico,
  webmanifest
]

excludeFiles: [
  '' # Special Folders like .git and .DS_Store
]

excludeFolders: [
  scratch,
  data,
  templates
]

# This contains every pattern that the program can use
patterns: {
  command: '{{\s*(?P<command>[^}}]+)\s*}}',
  calculate: 'calc\(\s*(?P<calculation>.+)\s*\)',
  compute: '{%\s*(?P<query>.+)[(](?P<value>[^)]+)[)]\s*%\s*{(?P<result>.+)\s*}\s*%\s*end\s?(?P=query)\s*%\s*}',
  yaml: '---(?P<yaml>.+?)-{3}(?P<markdown>.*)',
  operations: '(?P<left>.+)(?P<operator>[/*-+])(?P<right>.+)'
}

templates : {
  preview: 'project_preview_template.html',
  project: 'project_template.html',
  overview: 'projects_template.html',
  group: 'project_group_template.html'
}